### ISSUE TITLE
Style the pages in the 'register for an event' process

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#248]
This is in the proposal. They are civi pages so they won't be able to be styled as much as the rest of the site, but we should do what we can.

**Comment by angievanhegan** [comment]
@dilwarhussain I suggest we do the styling we can, then review it with Steve. Let me know if you want me to organise that. Thanks

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to review

**Comment by StephMSlack** [comment]
@dilwarhussain there seem to be some random extra fields displaying which are not in the profile. Am I missing something? Search for address is not one of the profile fields

![screen shot 2018-06-11 at 14 32 13](https://user-images.githubusercontent.com/32127102/41234539-65113230-6d84-11e8-8366-91a9a200d12d.png)

The continue button at the bottom left of the form - can this be in Pink as with the rest of the site and situated on the right (not left)

The error message when I didnt complete something was running over multiple lines

![screen shot 2018-06-11 at 14 37 15](https://user-images.githubusercontent.com/32127102/41234782-0c5447a8-6d85-11e8-882e-345783705385.png)

Can the None option be hidden for all of the session choices?- Note the sessions information should only appear for events which have sessions.

We need to style the confirmation screen as well. 
![screen shot 2018-06-11 at 14 41 12](https://user-images.githubusercontent.com/32127102/41235192-1e6d9de4-6d86-11e8-856d-5ca00fc415e0.png)

I went to confirm my registration and got an error message - this may link to the issues with pricing etc
 Sorry but we are not able to provide this at the moment.
The exit status code '127' says something went wrong: stderr: "sh: 1: /usr/bin/wkhtmltopdf: not found " stdout: "" command: /usr/bin/wkhtmltopdf --lowquality --margin-bottom '1cm' --margin-left '2cm' --margin-right '2cm' --margin-top '5cm' --orientation 'portrait' --page-height '841.89pt' --page-width '595.28pt' '/tmp/knp_snappy5b1e7d3ca45cf.html' '/tmp/knp_snappy5b1e7d3ca46b1.pdf'.
Return to home page.

**Comment by russ-manta** [comment]
@StephMSlack the registration error should now be fixed.  To  remove the none option you just need to make the price set field required - does this work for you?

**Comment by angievanhegan** [comment]
@StephMSlack The styling here is done.

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain I've started to look at the event page styling - could the first landing page be styled to align with the rest of the site as well?

![image](https://user-images.githubusercontent.com/32127102/41636300-96af0766-741b-11e8-9e87-cc59aa2084d1.png)

**Comment by StephMSlack** [comment]
@angievanhegan when I went to check the styling for the register process, I couldn't get beyond the page above when logged out

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain is there anyway that we can hide the name of the Civi Profile on the registration page?
![screen shot 2018-06-27 at 16 30 47](https://user-images.githubusercontent.com/32127102/41984038-89488ae0-7a27-11e8-96bc-44da8fe749d5.png)

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain When logged out I went to register for an event and got stuck at this page http://bgs-staging.mrmdev2.co.uk/civicrm/event-landing?reset=1&eid=51

Would it be possible for this page to look more like the rest of the site? Text then a pink login button, and text and a pink create an account button?

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain the 'search for address field is appearing twice. 
![screen shot 2018-07-03 at 12 48 38](https://user-images.githubusercontent.com/32127102/42218169-96c353a2-7ebf-11e8-9045-91c90ece1d4e.png)

**Comment by StephMSlack** [comment]
@russ-manta when testing this form I wanted to register 2 people. This bought up another section of text (see screen shot below) 'tell us about the other participants'

do we have any control where/when this text appears or is this dependent on Civi? Ideally 'tell us about the other participants should show before the card details are added.

<img width="826" alt="screen shot 2018-07-03 at 23 03 11" src="https://user-images.githubusercontent.com/32127102/42246754-b16494ea-7f15-11e8-9794-9b2f3e8c23c4.png">

**Comment by StephMSlack** [comment]
@russ-manta also - when I add a second participant the cost for registration is not updating. So it is staying at £50 for the merseyside event when I choose multiple registrations or one registration. Would this be linked to the payment processing or the Civi price sets?

**Comment by russ-manta** [comment]
@StephMSlack this is all Civi stuff, probably best to follow up with @daniellaveda

**Comment by daniellaveda** [comment]
@russ-manta cant log into the site to review the event
![screen shot 2018-07-04 at 14 11 09](https://user-images.githubusercontent.com/27422088/42278960-2ece91b4-7f94-11e8-8750-e1dff5322333.png)

**Comment by StephMSlack** [comment]
@russ-manta @daniellaveda - I can see the pages when logged in to the site as an admin, or when not logged in at all, but I get this same error when logged in as an editor or web user

**Comment by russ-manta** [comment]
@daniellaveda this should now be fixed. Can you take a nother look when you get a chance please?

**Comment by daniellaveda** [comment]
Hi @StephMSlack lets review tomorrow as i cant see how you created your price set - if you look at the one i just added to your price set it works fine 
![screen shot 2018-07-04 at 16 37 34](https://user-images.githubusercontent.com/27422088/42285934-f8818f16-7fa8-11e8-8933-ea8e4d91d237.png)

**Comment by StephMSlack** [comment]
@russ-manta some other things:
Search for address is coming through twice on the form - is this Civi or you?
I've updated the text in Civi for the event T&C. The T&C come from Civi, but the privacy policy is a link to the site (which isnt currently working). could we update the privacy link or remove the privacy policy link?

**Comment by StephMSlack** [comment]
@russ-manta just an FYI, when I tried booking as a speaker I got the error below. It may resolve itself when other issues are fixed, but just in case

![screen shot 2018-07-18 at 13 02 17](https://user-images.githubusercontent.com/32127102/42880108-02e971b6-8a8b-11e8-9cd0-066289da2d2f.png)

**Comment by russ-manta** [comment]
@StephMSlack that error was about missing pdf functionality so should now be working as I fixed that for cpd and receipt certificates

**Comment by russ-manta** [comment]
@StephMSlack @daniellaveda I've just replicated the duplicate postcode field appearing on events on the Veda staging site: https://bgs-civicrm.vedacrm.co.uk/civicrm/event/register?reset=1&id=28  I'll create a new ticket for Veda in their system

**Comment by russ-manta** [comment]
@StephMSlack Event booking links are now working in that when clicking the link you get the appropriate url based on your career stage. To add some kind of popup where you get to confirm career stage will need some more scoping and on reflection is probably out of the original scope - can we discuss if this is needed for go live?

**Comment by StephMSlack** [comment]
@russ-manta thanks
When not logged in, the register online button currently takes you to the become a member page (which is not the right place). If a user is not logged in, is it possible to show a different RHS nugget which would be similar in style to the not logged in membership nugget? 
<img width="578" alt="screen shot 2018-07-31 at 11 47 53" src="https://user-images.githubusercontent.com/32127102/43455409-9b454792-94b7-11e8-92e9-868e3590a160.png">

**Comment by StephMSlack** [comment]
@russ-manta when going to make payment I am using the stripe test cards, I click continue, it processes and then returns to the same screen without progressing through to the confirmation page.

**Comment by StephMSlack** [comment]
@russ-manta @angievanhegan is it possible to add a line of text underneath the event sessions title?

It is important that you indicate which sessions you will be attending as at times our sessions reach capacity. Your choice is also linked to the confirmation of your CPD point allocation.

**Comment by StephMSlack** [comment]
@russ-manta - when we go to register additional participants the styling of one section of Civi doesnt seem to show/work in the same way. Is there anything that can be done? Screen shot below
![screen shot 2018-08-01 at 09 52 47](https://user-images.githubusercontent.com/32127102/43511803-45ac270a-9571-11e8-8581-740f917fe067.png)

**Comment by russ-manta** [comment]
@StephMSlack the radio buttons, yes we can sort this. The extra text is normally more of a civi thing but we can probably do it using some javascript

**Comment by StephMSlack** [comment]
@russ-manta I tried putting it in Civi in the pre help text field, but the formatting went awry... If there is somewhere better in Civi to put it, I can do that
![screen shot 2018-08-01 at 10 29 12](https://user-images.githubusercontent.com/32127102/43513521-d9acfa2a-9575-11e8-85a3-2bb5cbd0db89.png)

**Comment by russ-manta** [comment]
@cutlern can you look at this please ' Fix display of radios on Event additional participant:'

**Comment by russ-manta** [comment]
@StephMSlack ' Fix display of radios on Event additional participant:' is now fixed on staging.

**Comment by dilwarhussain** [comment]
"It's related to the display of session choices for multiple day meetings
We shouldn't see Day 2 and Day 3 sessions if only Day 1 selected"

[Issues with Registration - Autumn meeting.docx](https://github.com/MantaRayMedia/bgs/files/2277390/Issues.with.Registration.-.Autumn.meeting.docx)

**Comment by russ-manta** [comment]
@StephMSlack is this still a problem?

**Comment by StephMSlack** [comment]
@russ-manta it is still an issue when logged in as a non-admin user. I am getting an error message when clicking register online

**Comment by StephMSlack** [comment]
@angievanhegan @russ-manta did you see the comments @dilwarhussain added from Geraint on the 10th August "It's related to the display of session choices for multiple day meetings
We shouldn't see Day 2 and Day 3 sessions if only Day 1 selected" There is more detail around this comment in the word doc Dilwar added. 

The other points in the document around content have been fixed, and is there anything that can be done about the font type and font size of the content that is coming from CiviCRM?

**Comment by russ-manta** [comment]
@StephMSlack yes I added something to the end of Dilwar's comment above. In short I think this is one for Veda and needs to be done via Civi.

**Comment by StephMSlack** [comment]
@russ-manta if you could have a  quick look at consolidating the different fonts/font sizes on the confirmation screen that would be great.
I'll raise the ticket display issue with Veda
